name: Auto Backup on Push

on:
  push:
    branches: [ main ]

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Upload repository snapshot
        uses: actions/upload-artifact@v3
        with:
          name: backup-${{ github.run_number }}-${{ github.sha }}
          path: .
